package org.omg.PortableServer;


/**
* org/omg/PortableServer/ID_ASSIGNMENT_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Thursday, November 17, 2011 1:15:14 PM GMT-08:00
*/

public interface ID_ASSIGNMENT_POLICY_ID
{

  /**
  	 * The value representing ID_ASSIGNMENT_POLICY_ID.
  	 */
  public static final int value = (int)(19L);
}
